.\"
.\" Copyright (c) 2011-2020, Stefan Vogt, Brian Cassidy, and Frederic Cambus
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\"   * Redistributions of source code must retain the above copyright
.\"     notice, this list of conditions and the following disclaimer.
.\"
.\"   * Redistributions in binary form must reproduce the above copyright
.\"     notice, this list of conditions and the following disclaimer in the
.\"     documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd $Mdocdate: January 17 2020 $
.Dt LIBANSILOVE 3
.Os
.Sh NAME
.Nm libansilove
.Nd Library for converting ANSI, ASCII, and other formats to PNG
.Sh DESCRIPTION
.Nm
is a library to convert ANSi and artscene related file formats into PNG
images, supporting ANSI (.ANS), PCBoard (.PCB), Binary (.BIN), Artworx
(.ADF), iCE Draw (.IDF), Tundra (.TND) and XBin (.XB) formats.
.Pp
It creates size optimized 4-bit PNG files and supports 80x25 and 80x50
PC fonts (including all the 14 MS-DOS charsets), Amiga fonts, and
iCE colors.
.Pp
All library functions take a context, defined as an
.Em ansilove_ctx
structure in
.Pa include/ansilove.h :
.Bd -literal
struct ansilove_ctx {
        uint8_t *buffer;
        size_t maplen;
        size_t length;
        struct ansilove_png png;
        uint8_t error;
};
.Ed
.Pp
Options are passed to the different loaders using the
.Em ansilove_options
structure in
.Pa include/ansilove.h :
.Bd -literal
struct ansilove_options {
        bool diz;
        bool dos;
        bool icecolors;
        bool truecolor;
        int16_t columns;
        uint8_t font;
        uint8_t bits;
        uint8_t mode;
        uint8_t scale_factor;
};
.Ed
.Sh AUTHORS
.An -nosplit
.Nm
was written by
.An Stefan Vogt ,
.An Brian Cassidy ,
and
.An Frederic Cambus .
